[package]
name = "db-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
log = "0.4"
env_logger = "0.11"
memmap2 = "0.9"
nom = "7.1"
